

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MES.Models
{
    public class Workorder
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Workorder")]
        public string Number { get; set; }
        [DisplayName("Reference")]
        public int ReferenceId { get; set; }
        [DisplayName("Target Quantity")]
        public int? Quantity { get; set; }
        [DisplayName("Date")]
        public DateTime DateTime { get; set; }
        [DisplayName("Generated By Machine")]
        public int? EntryThroughMachineId { get; set; }
        public virtual Machine EntryThroughMachine { get; set; }
        public virtual Product Reference { get; set; }
        [DisplayName("Product Sequence Used")]
        public int UseProductSequenceId { get; set; }
        public ProductSequence UseProductSequence { get; set; }
    }
}
